### ISSUE TITLE
Issue Could not find PackageBaseAddress/3.0.0 Endpoint after successful publish

### ISSUE THREAD

**Issue by Hdom** [miclip/nuget-resource#3]
Hello, when I try to push out the package it successfully uploads it to our nuget repo and then it fails on a second step. 

The code:
```
  - name: nuget-out
    type: nuget 
    source:
      nuget_source: {{nuget-source}}
      nuget_apikey: {{nuget-api-key}}
      package_id: {{package-id}}
      prerelease: true
```
```
    - put: nuget-out
      params: 
        package_path: build-output/*.nupkg
```
Error:
```
failed to get download url from api
Could not find PackageBaseAddress/3.0.0 Endpoint
```
It seems that our nuget repo does not have the PackageBaseAddress Endpoint. 
Is there any way to skip this download?
